version: 2

jobs:
  develop:
    docker:
      - image: ncino/ci-sfdx

    environment:
      - SFDX_AUTOUPDATE_DISABLE: true

    steps:
      - run:
          name: Test
          Command: sfdx force:auth:jwt:grant -h

  master:
    docker:
      - image: ncino/ci-sfdx

    environment:
      - SFDX_AUTOUPDATE_DISABLE: true

    steps:
      - checkout

      - run:
          name: Connect Sandbox
          command: sfdx force:auth:jwt:grant -i 3MVG910YPh8zrcR1yVy5MQ5lXneNWkYGo6gIN96ct1XJdxqCqbZb9YuGFXFTY5BMFAG4iIVcU1l.ZXuh_W4y8 -f .deploy/server.key -u maintenance@linkoff.bousai.ccideploy -s -a Sandbox --instanceurl https://test.salesforce.com --loglevel trace

      - run:
          name: Change to metadataAPI
          command: sfdx force:source:convert -d src

      - run:
          name: Deploy Verify
          command: |
            sfdx force:mdapi:deploy -c -l RunAllTestsInOrg -d src -u Sandbox | tee out.log
            drs=`grep Status: out.log | tr -d ' ' | cut -d ':' -f 2`
            if [ ${drs} = "Failed" ]; then
              cat out.log
              exit 1
            fi

            jid=`grep jobid out.log | head -1 | tr -d ' ' | cut -d ':' -f 2`
            crs=

            while [ -z "${crs}" ]
            do
              sfdx force:mdapi:deploy:report -u Sandbox -i ${jid} -w 1 | tee out.log
              crs=`grep finished out.log`
            done
            crs=`grep Status: out.log | tail -1 | tr -d ' ' | cut -d ':' -f 2`
            if [ ${crs} = "Failed" ]; then
              cat out.log
              exit 1
            else
              echo 'Verify OK'
            fi

      - run:
          name: Deploy
          Command: |
            sfdx force:mdapi:deploy -d src -u Sandbox | tee out.log
            drs=`grep Status: out.log | tr -d ' ' | cut -d ':' -f 2`
            if [ ${drs} = "Failed" ]; then
              cat out.log
              exit 1
            fi

            jid=`grep jobid out.log | head -1 | tr -d ' ' | cut -d ':' -f 2`
            crs=

            while [ -z "${crs}" ]
            do
              sfdx force:mdapi:deploy:report -u Sandbox -i ${jid} -w 1 | tee out.log
              crs=`grep finished out.log`
            done
            crs=`grep Status: out.log | tail -1 | tr -d ' ' | cut -d ':' -f 2`
            if [ ${crs} = "Failed" ]; then
              cat out.log
              exit 1
            else
              echo 'Deploy OK'
            fi

workflows:
  version: 2
  build_master:
    jobs:
      - master:
          filters:
            branches:
              only: master

  build_develop:
    jobs:
      - develop:
          filters:
            branches:
              only: develop
