version: 2
jobs:
  build:
    docker:
      - image: dancinllama/dockerdx

    steps:
      - checkout

      - run:
          name: Connect Sandbox
          command: sfdx force:auth:jwt:grant -i 3MVG9d8..z.hDcPLpmFuO54S6afwMRd7PN26g3hMfPUZiRYPEFyl4o00T4isazN5SrKuEqcC7JG1UveXd2eOS -f .deploy/server.key -u yoshinobu.tomino@gmail.com -s -a Sandbox

      - run:
          name: Change to metadataAPI
          command: sfdx force:source:convert -d src

      - run:
          name: Deploy Check
          command: sfdx force:mdapi:deploy -c -d src -u Sandox

